#!/bin/bash

if [ ! -e $HOME/Desktop/WELCOME/Activity_Monitor.txt ]; then
	cp $HOME/.bin/Activity_Monitor.txt $HOME/Desktop/WELCOME/Activity_Monitor.txt
fi

if [ ! -e $HOME/Desktop/WELCOME/Bocal.pdf ]; then
	cp $HOME/.bin/Bocal.pdf $HOME/Desktop/WELCOME/Bocal.pdf
fi
