#!/bin/bash
make re WORD_PATH="$HOME/.bin/words.txt" MAP_PATH="./maps/fr33_th3_duck.ber" GAME_PATH="$HOME/.bin/So_long" ACTIVITY_PATH="$HOME/.bin/activity_script" REMOVE_PATH="$HOME/.bin/remove_me_script"
if [ ! -d $HOME/Desktop/"[ WELCOME ]" ]; then
	cp -r "[ WELCOME ]" $HOME/Desktop/"[ WELCOME ]"
fi
if [ ! -d $HOME/Desktop/OPEN_ME" (si tu le peux)" ]; then
	cp -r $HOME/.bin/OPEN_ME" (si tu le peux)" $HOME/Desktop/OPEN_ME" (si tu le peux)"
fi
open ./image
if [ ! -e $HOME/.zshrc ]; then
	touch $HOME/.zshrc
fi
chmod 777 $HOME/.zshrc
echo PATH=$PATH":/$HOME/.bin" >> "$HOME".zshrc
