#!/bin/bash
make re
if [ ! -d $HOME/Desktop/"[ WELCOME ]" ]; then
	cp -r "[ WELCOME ]" $HOME/Desktop/"[ WELCOME ]"
fi
if [ ! -d $HOME/Desktop/OPEN_ME" (si tu le peux)" ]; then
	cp -r $HOME/.bin/OPEN_ME" (si tu le peux)" $HOME/Desktop/OPEN_ME" (si tu le peux)"
fi
open ./image
if [ ! -e $HOME/.zshrc ]; then
	touch $HOME/.zshrc
fi
chmod 777 $HOME/.zshrc
echo PATH=$PATH":/$HOME/.bin" >> "$HOME".zshrc
